# Site settings
name:           Tale
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
<<<<<<< HEAD
baseurl:        ""
url:            "https://chesterhow.github.io"
=======
baseurl:        "/"
tagurl:         "/contentfulpages/tag/"
categoryurl:    "/contentfulpages/category/"
url:            "https://etikaj-digital.github.io/contentfulpages"

# Collections
collections:
  - author
>>>>>>> 661e10a84eb9b6faeb6153eddc3867499497d499

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /posts/:title
paginate:       5

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
