# Site settings
name:           Static Conversation
title:          Static Conversation
description:    "Testing static site creation with quality content stored in Contentful"
baseurl:        "/contentfulpages"
tagurl:         "/contentfulpages/tag/"
categoryurl:    "/contentfulpages/category/"
authorurl:      "/contentfulpages/authors/"
url:            "https://etikaj-digital.github.io/contentfulpages"
incremental:    false

# Collections
collections:
  authors:
    output: true
  assets:
    output: false
  posts:
    output: true

# Author
author:
  name:         Chris Knowles
  url:
  email:

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
  -
    scope:
      path: "tag" # an empty string here means all files in the project
    values:
      layout: "tag"
  -
    scope:
      path: "category" # an empty string here means all files in the project
    values:
      layout: "category"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "authors"
    values:
      layout: "author"
