# Site settings
name:           Tale
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/contentfulpages/"
tagurl:         "/contenfulpages/tag/"
categoryurl:    "/contentfulpages/category/"
url:            "https://etikaj-digital.github.io/contentfulpages"

# Collections
collections:
  - authors
  - assets

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /posts/:title
paginate:       25

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
  -
    scope:
      path: "tag" # an empty string here means all files in the project
    values:
      layout: "tag"
  -
    scope:
      path: "category" # an empty string here means all files in the project
    values:
      layout: "category"
